version: '3'

services:
  cloudappcore1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ConnectionString=Server=tcp:testappserver01.database.windows.net,1433;Initial Catalog=testapps01;Persist Security Info=False;User ID={your_username};Password={your_password};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
      #Server=sql.data;Database=Microsoft.eJobContainer.Services.JobsDb;User=sa;Password=Pass@word
    ports:
      - "80"

  #sql.data:
  #  environment:
  #    - SA_PASSWORD=Pass@word
  #    - ACCEPT_EULA=Y
  #  ports:
  #    - "5433:1433"
  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
#networks:
#  default:
#    external:
#      name: nat
