version: '3'

services:
  cloudappcore1:
    image: cloudappcore1
    build:
      context: .
      dockerfile: CloudAppCore1/Dockerfile
    #depends_on:
    #  - sql.data

  #sql.data:
  #  image: microsoft/mssql-server-linux:2017-latest

  webmvc:
    image: webmvc
    build:
      context: .
      dockerfile: WebMvc\Dockerfile

  webapp:
    image: webapp
    build:
      context: .
      dockerfile: ..\WebApp\Dockerfile

